language: python
python:
- '3.6'
env:
  global:
  - secure: r1eO4dO8tIydHqbJSooHES4F81czOoMo5xZkbL/X2vDBr36PuYzDjV5ofAiMBG0psSpylhWZqheQ7T8noGODKZ2RT4qxyyAifBQ8jAEFIWR1zHmD4T+R1IUmsPIln1Xcou/A3ts4s0fonJ4HO/DTFvqRRLbj4Ug5iI8ehZJFYRyyhTYLj0u9aW6UmXH+32uRPE8SokwNwM9IMMKa5UJSSQbyWEAn3XWwhASSoGt20BmVzowwoq1cFSGj6mZ3qsMWFZFRgQNzsym+se/Qa08V/N6ANDITnuQYLeYjMMVhJ182GNVcm6P6CADGBzvT+4KofgNTVnAJTVXA6foZlzV9Aqdm05Hu3ada4EP1T9nKI3cuTYT6NNB5fFGmBSaNuHcRyn3l3UaJ9hJKw5oAuaKBswhGZG474Ix4R1vX4Le0zoqaIDa2YXEVTpGDRyVeXwXfiY7U+GJmYDVluDvZa6iFVbu3+x7YvOtPD905PAU/lFKKpdJnZ3B24A6A0medvhTF0RryTzvnR94es48av7MjRiCVfRZ3eRG4C3VBdVJ6/+69E8U3U0hESpzmYf78h/gE+lfVgyuWE4bTcEvuy/Y0qoTPCdFjw3P+rif2jcqlWbg5r9aV9GkgNFNIPoA6z5faM6A0wMmuQPtVJRyQJEFtZmtaxauu12HqHYdPmLvXI3c=
branches:
  only:
  - master
script:
- python tests/test_simple.py
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
after_success:
- ". scripts/push.sh"
deploy:
  provider: releases
  api_key:
    secure: tulWglIHYyz+7jR7qRgdn7hLMU8v5RYuO5uuo9Zk0QuG7EPOXqeLf7PlKgEJj6L2hKjB2zUOO7j1j3IFe8H+kf7L1yAMCFU0/NjVpNgaOam2MtLZr44tzGTwQKN09I2w7CGR7wb4dskFvUFx2Yq4Whk/cavZE6kF4rKmLvOnBCEPxBabIA+s8a9uEsvbiposDe+XlwphjQHGsoW3f1G3rvaKaedm51wOqnixlT0jGsoUl6VbREeXZpHzWkjJOFDLTWWCV1XKRAcxQUxO3XDloAJhgdaoG+TXfUiH7rCBeV/aQRyuqJMRQ1LOga8uH9WQivFTxoyoIWP8YOW4q390bbVn1EgI5LRlDDmcTD+FsT1RHINDWOiwxt1YeAlG9+4LFUh5rn4rWFxg7s9hVjZ2N5uNjSTOo5VRqp200n88JgbY6CiymndxqY4aFCNpF6GMxByn1Iy8RkXsuK5XK590bnH2cq0zY9cb+3MZKwhVlYtMuJg7tyz8UwTsIXhB/rkDRhgwsjdRmRd7uNPOMQo9p2CkxgX0OKSHSoUmNiaVRKXD85ClifL4dwvb5iWUFE9ZYCLinJ+2xzANeqjc78Jeegiw3RIzwxuQ5FdtezJSSTb3Famgl9a1fwrd7woGGAoWshKv5CtRJjRiY82qfLtGWGjpyOPqn6zSj8Am1lIJ2rE=
  file: dist/sample-1.2.0.tar.gz
  on:
    repo: artzag/sampleproject
